### PR TITLE
crate student app

### PR DESCRIPTION
**Pull request by Nozimjon07**
hammasi togri!!!!

### CODE REVIEW

**Review by 070DBEK — APPROVED** [review]
Good luck (+.+)

**Review by 070DBEK — APPROVED** [review]

**Comment by Nozimjon07** [comment]
Hammasi togri!!

**Comment by Nozimjon07** [comment]
Hammasi togri!!!!

**Comment by 070DBEK** [comment]
Good project bro (dev_1)

**Pull request merged**
